spring.datasource.url=jdbc:postgresql://localhost:5432/campus_db
spring.datasource.username=campus_user
spring.datasource.password=campus_pass

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8081